### ISSUE TITLE
[all] Release Lit 3.0

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#3848]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Related issues and PRs:
- https://github.com/lit/lit/issues/3774
- RFC: https://github.com/lit/rfcs/pull/16
- https://github.com/lit/lit.dev/issues/1074

### Tasks

- [x] Blog post
- [x] Tweets
- [x] Fix all prerelease references in code and package.json
- [x] Clean up READMEs
- [x] Merge `3.0` into `main`

### Alternatives and Workarounds

N/A

**Comment by augustjk** [comment]
We did it! 🎉 🚀
